# Generated by Django 4.2.3 on 2023-07-22 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular advertiser', primary_key=True, serialize=False)),
                ('Advertiser_Name', models.CharField(max_length=50)),
                ('Advertiser_Contact_Manager_Name', models.CharField(max_length=50)),
                ('Advertiser_Contact_Email', models.CharField(max_length=50, null=True)),
                ('Advertiser_Contact_Phone', models.CharField(max_length=50, null=True)),
                ('Advertiser_Country', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular advertiser', primary_key=True, serialize=False)),
                ('PromoCompanyName', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description of the PromotionsCompany', max_length=1000)),
                ('PromoCompany_Due_Date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('on', 'Turn On'), ('off', 'Turn Off')], default='on', help_text='PromoCompany Turn On', max_length=3)),
                ('Advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser')),
            ],
            options={
                'ordering': ['status'],
                'permissions': (('can_mark_turn_status_PromoCompany', 'Set Promo Company turn on/off status'), ('can_change_PromoCompany_name', 'Change PromoCompany Name')),
            },
        ),
    ]
