# Generated by Django 4.2.3 on 2023-07-31 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular advertiser', primary_key=True, serialize=False)),
                ('advertiser_name', models.CharField(max_length=50)),
                ('advertiser_image', models.ImageField(null=True, upload_to='avertiserimages/')),
                ('advertiser_contact_manager_name', models.CharField(max_length=50)),
                ('advertiser_contact_email', models.EmailField(max_length=254, null=True)),
                ('advertiser_contact_phone', models.CharField(max_length=50, null=True)),
                ('advertiser_country', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular advertiser', primary_key=True, serialize=False)),
                ('promo_company_name', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description of the PromotionsCompany', max_length=1000)),
                ('promo_company_valid_from', models.DateField(blank=True, null=True)),
                ('promo_company_valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('on', 'Turn On'), ('off', 'Turn Off')], default='on', help_text='PromoCompany Turn On', max_length=3)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser')),
            ],
            options={
                'ordering': ['status', 'promo_company_valid_from', 'promo_company_valid_to'],
                'permissions': (('can_mark_turn_status_PromoCompany', 'Set Promo Company turn on/off status'), ('can_change_PromoCompany_name', 'Change PromoCompany Name')),
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for promocode', primary_key=True, serialize=False)),
                ('promocode_entity', models.CharField(max_length=20, null=True)),
                ('promocode_url', models.CharField(max_length=500, null=True)),
                ('promocode_decription', models.CharField(max_length=200, null=True)),
                ('promocode_image', models.ImageField(null=True, upload_to='promocodeimages/')),
                ('promocode_valid_from', models.DateField(blank=True, null=True)),
                ('promocode_valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('on', 'Turn On'), ('off', 'Turn Off')], default='on', help_text='Promocode Turn On', max_length=3)),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser')),
                ('promo_company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.promocompany')),
            ],
            options={
                'ordering': ['status', 'promocode_valid_from', 'promocode_valid_to'],
                'permissions': (('can_mark_turn_status_ promocode', 'Set promocode turn on/off status'), ('can_change_promocode', 'Change promocode')),
            },
        ),
    ]
