# Generated by Django 4.2.3 on 2023-07-31 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='promocode_image',
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='advertiser_image',
            field=models.ImageField(blank=True, null=True, upload_to='avertiserimages/'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser'),
        ),
    ]
