# Generated by Django 4.2.3 on 2023-07-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocompany',
            options={'ordering': ['PromoCompany_Due_Date'], 'permissions': (('can_mark_turn_status_PromoCompany', 'Set Promo Company turn on/off status'), ('can_change_PromoCompany_name', 'Change PromoCompany Name'))},
        ),
    ]
