# Generated by Django 4.2.3 on 2023-07-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_alter_promocompany_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocompany',
            options={'ordering': ['status', 'PromoCompany_Due_Date'], 'permissions': (('can_mark_turn_status_PromoCompany', 'Set Promo Company turn on/off status'), ('can_change_PromoCompany_name', 'Change PromoCompany Name'))},
        ),
    ]
