# Generated by Django 4.2.3 on 2023-08-01 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_remove_promocode_promocode_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDealsAffiliateLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for promocode', primary_key=True, serialize=False)),
                ('affiliatelink_entity', models.CharField(max_length=20, null=True)),
                ('affiliatelink_advertiser_url', models.CharField(max_length=500, null=True)),
                ('affiliatelink_cpa_url', models.CharField(max_length=500, null=True)),
                ('affiliatelink_decription', models.CharField(max_length=200, null=True)),
                ('affiliatelink_valid_from', models.DateField(blank=True, null=True)),
                ('affiliatelink_valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('on', 'Turn On'), ('off', 'Turn Off')], default='on', help_text='affiliatelink Turn On', max_length=3)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser')),
            ],
            options={
                'ordering': ['status', 'affiliatelink_valid_from', 'affiliatelink_valid_to'],
                'permissions': (('can_mark_turn_status_ affiliatelink', 'Set affiliatelink turn on/off status'), ('can_change_affiliatelink', 'Change affiliatelink')),
            },
        ),
    ]
