# Generated by Django 4.2.3 on 2023-07-22 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_alter_promocompany_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for promocode', primary_key=True, serialize=False)),
                ('promocode_entity', models.CharField(max_length=20, null=True)),
                ('promocode_url', models.CharField(max_length=500, null=True)),
                ('promocode_decription', models.CharField(max_length=200, null=True)),
                ('Promocode_valid_from', models.DateField(blank=True, null=True)),
                ('Promocode_valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('on', 'Turn On'), ('off', 'Turn Off')], default='on', help_text='Promocode Turn On', max_length=3)),
                ('Advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser')),
                ('PromoCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.promocompany')),
            ],
            options={
                'ordering': ['status', 'Promocode_valid_from', 'Promocode_valid_to'],
                'permissions': (('can_mark_turn_status_ promocode', 'Set promocode turn on/off status'), ('can_change_promocode', 'Change promocode')),
            },
        ),
    ]
