# Generated by Django 4.2.3 on 2023-08-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_hotdealsaffiliatelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdealsaffiliatelink',
            name='affiliatelink_image',
            field=models.ImageField(blank=True, null=True, upload_to='affiliatelinkimages/'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='promocode_image',
            field=models.ImageField(blank=True, null=True, upload_to='promocodeimages/'),
        ),
    ]
