# Generated by Django 4.2.3 on 2023-07-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocompany',
            options={'ordering': ['status', 'PromoCompany_valid_from', 'PromoCompany_valid_to'], 'permissions': (('can_mark_turn_status_PromoCompany', 'Set Promo Company turn on/off status'), ('can_change_PromoCompany_name', 'Change PromoCompany Name'))},
        ),
        migrations.RenameField(
            model_name='promocompany',
            old_name='PromoCompany_Due_Date',
            new_name='PromoCompany_valid_from',
        ),
        migrations.AddField(
            model_name='promocompany',
            name='PromoCompany_valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
