# Generated by Django 4.2.3 on 2023-08-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_hotdealsaffiliatelink_affiliatelink_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdealsaffiliatelink',
            name='affiliatelink_entity',
        ),
    ]
