# Generated by Django 4.2.3 on 2023-08-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_remove_hotdealsaffiliatelink_affiliatelink_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promocode_cpa_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotdealsaffiliatelink',
            name='affiliatelink_decription',
            field=models.TextField(null=True),
        ),
    ]
