# Generated by Django 4.2.3 on 2023-07-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_alter_promocompany_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='PromoCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.promocompany'),
        ),
    ]
