# Generated by Django 4.2.3 on 2023-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0006_promocode_promocode_cpa_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='advertiser_image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
