# Generated by Django 4.2.3 on 2023-07-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0006_advertiser_promocompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='PromoCompany',
        ),
    ]
