# Generated by Django 4.2.3 on 2023-09-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_advertiser_advertiser_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='advertiser_image_aws',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
