# Generated by Django 4.2.3 on 2023-09-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0008_advertiser_advertiser_image_aws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='advertiser_image_aws',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='advertiser_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
