# Generated by Django 4.2.3 on 2023-07-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0009_alter_promocode_promocompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocompany',
            name='Advertiser',
            field=models.ForeignKey(limit_choices_to={'id__exact': 'self.Advertiser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser'),
        ),
    ]
