# Generated by Django 4.2.3 on 2023-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0009_alter_advertiser_advertiser_image_aws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='xmls/'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='xml_file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
