# Generated by Django 4.2.3 on 2023-10-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0010_advertiser_xml_file_advertiser_xml_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promocode_external_uid',
            field=models.CharField(blank=True, help_text='Unique external ID for promocode', max_length=20, null=True),
        ),
    ]
