# Generated by Django 4.2.3 on 2023-07-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0010_alter_promocompany_advertiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='Advertiser',
            field=models.ForeignKey(limit_choices_to={'Advertiser': models.F('Advertiser')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='PromoCompany',
            field=models.ForeignKey(limit_choices_to={'Advertiser': models.F('Advertiser')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.promocompany'),
        ),
    ]
