# Generated by Django 4.2.3 on 2023-07-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0011_alter_promocode_advertiser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='Advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='PromoCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.promocompany'),
        ),
        migrations.AlterField(
            model_name='promocompany',
            name='Advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.advertiser'),
        ),
    ]
