# Generated by Django 4.2.3 on 2023-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0011_promocode_promocode_external_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='promocode_entity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
