# Generated by Django 4.2.3 on 2023-10-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0012_alter_promocode_promocode_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='advertiser_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='advertiser_contact_manager_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='advertiser_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='advertiser_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
