# Generated by Django 4.2.3 on 2023-10-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0013_alter_advertiser_advertiser_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='advertiser_cpa_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
