# Generated by Django 4.2.3 on 2023-10-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0014_advertiser_advertiser_cpa_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='promo_company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promo.promocompany'),
        ),
    ]
