"""
Django settings for couponforyou project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-taqb=0^!8$-r7v$-535#u^eb#*s97443$tg$59$v2b%sfoyjna'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['coupon4you-4b9fbb86e541.herokuapp.com',
'https://coupon4you-4b9fbb86e541.herokuapp.com',
                '127.0.0.1',
                 'chrome-extension://lkjcpgjjhggkdoojacjnhckaofljnjkn',
                 'chrome-extension://koghiapaagjoioohnieameekalpfeekk',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'promo.apps.PromoConfig',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ORIGIN_WHITELIST = [
    'chrome-extension://lkjcpgjjhggkdoojacjnhckaofljnjkn',
    'chrome-extension://koghiapaagjoioohnieameekalpfeekk',
]

CORS_ALLOWED_ORIGINS = [
    'chrome-extension://lkjcpgjjhggkdoojacjnhckaofljnjkn',
    'chrome-extension://koghiapaagjoioohnieameekalpfeekk',
]

CORS_ALLOW_HEADERS = [
    'Authorization',
]

CSRF_TRUSTED_ORIGINS = [
    'chrome-extension://lkjcpgjjhggkdoojacjnhckaofljnjkn',
    'chrome-extension://koghiapaagjoioohnieameekalpfeekk',
    # Другие источники
]


ROOT_URLCONF = 'couponforyou.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'couponforyou.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# settings.py

# Определите URL для статических файлов
STATIC_URL = '/static/'

# Определите путь к статическим файлам для развертывания в продакшн-среде
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Определите пути к директориям с вашими собственными статическими файлами
# Здесь не должно быть параметра STATIC_ROOT
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'